version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.6.5
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base image
          command: packer validate ./base/ubuntu_20.04.pkr.hcl
  build-base:
    docker:
      - image: hashicorp/packer:1.6.5
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build base
          command: packer build ./base/ubuntu_20.04.pkr.hcl
          no_output_timeout: 30m

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          context:
            - Terraform State
          requires:
            - validate
